# Generated by Django 4.0.6 on 2022-10-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='email_id',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
