# Generated by Django 4.0.6 on 2022-10-09 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restraunts', '0002_restraunt_contact_no_restraunt_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='res_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
